#!/bin/bash
# file: rs_ipu6_d457_bind.sh
# This script used for binding media links of v4l2 subdevice entities
# The configuration we had is ISX031 mux and IPU6 entities.
# _______  _______  _______  _______  _________
# |depth|->| mux |->|CSI-2|->|BESOC|->|capture|
# |_____|  |_____|  |_____|  |_____|  |_______|
#
# Full graph can be viewed on http://magjac.com/graphviz-visual-editor/
# media graph links can be generated by running 'media-ctl --print-dot'
#
# Dependency: v4l-utils
v4l2_util=$(which v4l2-ctl)
media_util=$(which media-ctl)
if [ -z ${v4l2_util} ]; then
  echo "v4l2-ctl not found, install with: sudo apt install v4l-utils"
  exit 1
fi
# enable metadata capture nodes for default
metadata_enabled=1
while [[ $# -gt 0 ]]; do
  case $1 in
    -q|--quiet)
      quiet=1
      shift
    ;;
    -m|--mux)
      shift
      mux_param=$1
      shift
    ;;
    -n|--no-metadata)
      metadata_enabled=0
      shift
    ;;
    -h|--help)
      echo "-q -m -n -h" 
    ;;
    -f)
      fmt="$2"
      shift
      ;;
    *)
      quiet=0
      shift
    ;;
    esac
done

fmt="${fmt:-[fmt:UYVY8_1X16/1920x1536@1/60 field:none]}"

# mapping for ISX031 mux entity to IPU6 BE SOC entity matching.
declare -A media_mux_capture_link=( [a]='' [b]='1 ' [c]='2 ' [d]='3 ' [e]='4 ' [f]='5 ' [g]='' [h]='1 '  [i]='2 ' [j]='3 ' [k]='4 ' [l]='5 ')
# mapping for ISX031 mux entity to IPU6 CSI-2 entity matching.
declare -A media_mux_csi2_link=( [a]=0 [b]=1 [c]=2 [d]=3 [e]=4 [f]=5 [g]=0 [h]=1 [i]=2 [j]=3 [k]=4 [l]=5)

# all available ISX031 muxes, each one represent physically connected camera.
# muxes a, b, c, d, e, f  usually single link cameras
# muxes g, h, i, i, k, l is aggregated link cameras, 'a' coupled to 'g'

mux_list=${mux_param:-'a b c d e f g h i j k l'}

# Find media device.
# For case with usb camera plugged in during the boot,
# usb media controller will occupy index 0
mdev=$(${v4l2_util} --list-devices | grep -A1 ipu6 | grep media)
[[ -z "${mdev}" ]] && exit 0

out() {
  [[ $quiet -eq 0 ]] && echo -n "${@}    " >&2
  "${@}"
  [[ $quiet -eq 0 ]] && echo "        RET=$?" >&2
}

media_ctl_cmd="${media_util} -d ${mdev}"
# media-ctl -r # <- this can be used to clean-up all bindings from media controller
# cache media-ctl output
dot=$($media_ctl_cmd --print-dot)

# ISX031 MUX. Can be {a, b, c, d} + Aggregated {e, f, g, h}.
for mux in $mux_list; do
  is_mux=$(echo "${dot}" | grep "ISX031 mux ${mux}")
  # skip for non-existing muxes
  [[ -z $is_mux ]] && continue;

  [[ $quiet -eq 0 ]] && echo "Bind ISX031 mux ${mux} .. " >&2

  csi2_be_soc="CSI2 BE SOC ${media_mux_csi2_link[${mux}]}"

  csi2="CSI-2 ${media_mux_csi2_link[${mux}]}"
  # capture pad
  be_soc_cap="BE SOC ${media_mux_capture_link[${mux}]}capture"

  cap_pad=0
  # bind (enable) link CSI-2 pad 1 to BE-SOC pad 0
  out $media_ctl_cmd -l "\"Intel IPU6 ${csi2}\":1 -> \"Intel IPU6 ${csi2_be_soc}\":0[1]"
  # bind (enable) link ISX031 mux pad 0 to CSI-2 pad 0
  out $media_ctl_cmd -l "\"ISX031 mux ${mux}\":0 -> \"Intel IPU6 ${csi2}\":0[1]"

  cap_pad=0
  if [ "${mux}" \> "f" ]; then
    cap_pad=6
  fi

  # DEPTH video streaming node
  out $media_ctl_cmd -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+1)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+0))\":0[5]"
  # # DEPTH metadata node
  # if [[ $metadata_enabled -eq 1 ]]; then
  #   out $media_ctl_cmd -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+2)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+1))\":0[5]"
  # fi

  # # RGB link video streaming node
  # out $media_ctl_cmd -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+3)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+2))\":0[5]"
  # # RGB metadata node
  # if [[ $metadata_enabled -eq 1 ]]; then
  #   out $media_ctl_cmd -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+4)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+3))\":0[5]"
  # fi

  # # IR link video streaming node
  # out $media_ctl_cmd -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+5)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+4))\":0[5]"

  # # IMU link streaming node
  # out $media_ctl_cmd -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+6)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+5))\":0[5]"

  out $media_ctl_cmd -V "\"ISX031 yuv ${mux}\":0 ${fmt}"
  #out $media_ctl_cmd -V "\"ISX031 mux ${mux}\":1 ${fmt}"
  out $media_ctl_cmd -V "\"ISX031 mux ${mux}\":0 ${fmt}"
  #out $media_ctl_cmd -V "\"Intel IPU6 ${csi2}\":0 ${fmt}"
  #out $media_ctl_cmd -V "\"Intel IPU6 ${csi2}\":1 ${fmt}"
  #out $media_ctl_cmd -V "\"Intel IPU6 ${csi2_be_soc}\":0 ${fmt}"
  out $media_ctl_cmd -V "\"Intel IPU6 ${be_soc_cap} $((${cap_pad}+0))\":0 ${fmt}"

  cap_dev=$($media_ctl_cmd -e "Intel IPU6 ${be_soc_cap} $((${cap_pad}+0))")
  ln -snf ${cap_dev} /dev/video-isx031-${mux}

done
